import psycopg2 as pg

db = pg.connect(
    database='movies',
    user='postgres',
    password='password',
    host='localhost',
    port='5432'
)


def create_db(db):
    db.autocommit = True
    with db.cursor() as cursor:
        sql_commands = ["DROP TABLE IF EXISTS topfilm;",
                        "DROP TABLE IF EXISTS oscars;",
                        "DROP TABLE IF EXISTS authors;",
                        "DROP TABLE IF EXISTS trivia;",
                        "DROP TABLE IF EXISTS scores;",
            """CREATE TABLE topfilm 
(
    id INT,
    name	VARCHAR(512)
);""",
"""CREATE TABLE trivia 
(
    id	INT,
    year	INT,
    genre	VARCHAR(512),
    country	VARCHAR(512)
);""",
"""CREATE TABLE scores 
(
    id	INT,
    rating	FLOAT
);""",
"""CREATE TABLE authors 
(
    id	INT,
    director	VARCHAR(512)
);""",
"""CREATE TABLE actors 
(
    id	INT,
    actor	VARCHAR(512)
);""",
"""CREATE TABLE oscars
        (
            year	INT,
            film 	VARCHAR(300)
        );"""]
        for sql_command in sql_commands:
            cursor.execute(sql_command)

def fill_topfilm(db):
    db.autocommit = True
    with db.cursor() as cursor:
        sql_commands = ["INSERT INTO topfilm (id, name) VALUES ('1', 'Побег из Шоушенка');",
"INSERT INTO topfilm (id, name) VALUES ('2', 'Крёстный отец');",
"INSERT INTO topfilm (id, name) VALUES ('3', 'Тёмный рыцарь');",
"INSERT INTO topfilm (id, name) VALUES ('4', 'Крёстный отец 2');",
"INSERT INTO topfilm (id, name) VALUES ('5', '12 разгневанных мужчин');",
"INSERT INTO topfilm (id, name) VALUES ('6', 'Список Шиндлера');",
"INSERT INTO topfilm (id, name) VALUES ('7', 'Властелин колец: Возвращение короля');",
"INSERT INTO topfilm (id, name) VALUES ('8', 'Криминальное чтиво');",
"INSERT INTO topfilm (id, name) VALUES ('9', 'Властелин колец: Братство Кольца');",
"INSERT INTO topfilm (id, name) VALUES ('10', 'Хороший, плохой, злой');",
"INSERT INTO topfilm (id, name) VALUES ('11', 'Форрест Гамп');",
"INSERT INTO topfilm (id, name) VALUES ('12', 'Бойцовский клуб');",
"INSERT INTO topfilm (id, name) VALUES ('13', 'Начало');",
"INSERT INTO topfilm (id, name) VALUES ('14', 'Властелин колец: Две крепости');",
"INSERT INTO topfilm (id, name) VALUES ('15', 'Звёздные войны. Эпизод V: Империя наносит ответный удар');",
"INSERT INTO topfilm (id, name) VALUES ('16', 'Матрица');",
"INSERT INTO topfilm (id, name) VALUES ('17', 'Славные парни');",
"INSERT INTO topfilm (id, name) VALUES ('18', 'Пролетая над гнездом кукушки');",
"INSERT INTO topfilm (id, name) VALUES ('19', 'Семь');",
"INSERT INTO topfilm (id, name) VALUES ('20', 'Семь самураев');",
"INSERT INTO topfilm (id, name) VALUES ('21', 'Эта прекрасная жизнь');",
"INSERT INTO topfilm (id, name) VALUES ('22', 'Молчание ягнят');",
"INSERT INTO topfilm (id, name) VALUES ('23', 'Город Бога');",
"INSERT INTO topfilm (id, name) VALUES ('24', 'Спасти рядового Райана');",
"INSERT INTO topfilm (id, name) VALUES ('25', 'Жизнь прекрасна');",
"INSERT INTO topfilm (id, name) VALUES ('26', 'Зелёная миля');",
"INSERT INTO topfilm (id, name) VALUES ('27', 'Интерстеллар');",
"INSERT INTO topfilm (id, name) VALUES ('28', 'Звёздные войны. Эпизод IV: Новая надежда');",
"INSERT INTO topfilm (id, name) VALUES ('29', 'Терминатор 2: Судный день');",
"INSERT INTO topfilm (id, name) VALUES ('30', 'Назад в будущее');",
"INSERT INTO topfilm (id, name) VALUES ('31', 'Унесённые призраками');",
"INSERT INTO topfilm (id, name) VALUES ('32', 'Психо');",
"INSERT INTO topfilm (id, name) VALUES ('33', 'Пианист');",
"INSERT INTO topfilm (id, name) VALUES ('34', 'Леон');",
"INSERT INTO topfilm (id, name) VALUES ('35', 'Паразиты');",
"INSERT INTO topfilm (id, name) VALUES ('36', 'Король Лев');",
"INSERT INTO topfilm (id, name) VALUES ('37', 'Гладиатор');",
"INSERT INTO topfilm (id, name) VALUES ('38', 'Американская история Икс');",
"INSERT INTO topfilm (id, name) VALUES ('39', 'Отступники');",
"INSERT INTO topfilm (id, name) VALUES ('40', 'Подозрительные лица');",
"INSERT INTO topfilm (id, name) VALUES ('41', 'Престиж');",
"INSERT INTO topfilm (id, name) VALUES ('42', 'Касабланка');",
"INSERT INTO topfilm (id, name) VALUES ('43', 'Одержимость');",
"INSERT INTO topfilm (id, name) VALUES ('44', '1+1');",
"INSERT INTO topfilm (id, name) VALUES ('45', 'Могила светлячков');",
"INSERT INTO topfilm (id, name) VALUES ('46', 'Харакири');",
"INSERT INTO topfilm (id, name) VALUES ('47', 'Новые времена');",
"INSERT INTO topfilm (id, name) VALUES ('48', 'Однажды на Диком Западе');",
"INSERT INTO topfilm (id, name) VALUES ('49', 'Окно во двор');",
"INSERT INTO topfilm (id, name) VALUES ('50', 'Чужой');",
"INSERT INTO topfilm (id, name) VALUES ('51', 'Огни большого города');",
"INSERT INTO topfilm (id, name) VALUES ('52', 'Новый кинотеатр «Парадизо»');",
"INSERT INTO topfilm (id, name) VALUES ('53', 'Апокалипсис сегодня');",
"INSERT INTO topfilm (id, name) VALUES ('54', 'Помни');",
"INSERT INTO topfilm (id, name) VALUES ('55', 'Индиана Джонс: В поисках утраченного ковчега');",
"INSERT INTO topfilm (id, name) VALUES ('56', 'Джанго освобождённый');",
"INSERT INTO topfilm (id, name) VALUES ('57', 'ВАЛЛ-И');",
"INSERT INTO topfilm (id, name) VALUES ('58', 'Жизнь других');",
"INSERT INTO topfilm (id, name) VALUES ('59', 'Бульвар Сансет');",
"INSERT INTO topfilm (id, name) VALUES ('60', 'Тропы славы');",
"INSERT INTO topfilm (id, name) VALUES ('61', 'Сияние');",
"INSERT INTO topfilm (id, name) VALUES ('62', 'Великий диктатор');",
"INSERT INTO topfilm (id, name) VALUES ('63', 'Мстители: Война бесконечности');",
"INSERT INTO topfilm (id, name) VALUES ('64', 'Свидетель обвинения');",
"INSERT INTO topfilm (id, name) VALUES ('65', 'Чужие');",
"INSERT INTO topfilm (id, name) VALUES ('66', 'Красота по-американски');",
"INSERT INTO topfilm (id, name) VALUES ('67', 'Человек-паук: Через вселенные');",
"INSERT INTO topfilm (id, name) VALUES ('68', 'Доктор Стрейнджлав, или Как я перестал бояться и полюбил бомбу');",
"INSERT INTO topfilm (id, name) VALUES ('69', 'Топ Ган: Мэверик');",
"INSERT INTO topfilm (id, name) VALUES ('70', 'Тёмный рыцарь: Возрождение легенды');",
"INSERT INTO topfilm (id, name) VALUES ('71', 'Олдбой');",
"INSERT INTO topfilm (id, name) VALUES ('72', 'Джокер');",
"INSERT INTO topfilm (id, name) VALUES ('73', 'Амадей');",
"INSERT INTO topfilm (id, name) VALUES ('74', 'Храброе сердце');",
"INSERT INTO topfilm (id, name) VALUES ('75', 'История игрушек');",
"INSERT INTO topfilm (id, name) VALUES ('76', 'Тайна Коко');",
"INSERT INTO topfilm (id, name) VALUES ('77', 'Бесславные ублюдки');",
"INSERT INTO topfilm (id, name) VALUES ('78', 'Подводная лодка');",
"INSERT INTO topfilm (id, name) VALUES ('79', 'Мстители: Финал');",
"INSERT INTO topfilm (id, name) VALUES ('80', 'Принцесса Мононоке');",
"INSERT INTO topfilm (id, name) VALUES ('81', 'Однажды в Америке');",
"INSERT INTO topfilm (id, name) VALUES ('82', 'Умница Уилл Хантинг');",
"INSERT INTO topfilm (id, name) VALUES ('83', 'Твоё имя');",
"INSERT INTO topfilm (id, name) VALUES ('84', 'Реквием по мечте');",
"INSERT INTO topfilm (id, name) VALUES ('85', 'История игрушек: Большой побег');",
"INSERT INTO topfilm (id, name) VALUES ('86', 'Поющие под дождём');",
"INSERT INTO topfilm (id, name) VALUES ('87', '3 идиота');",
"INSERT INTO topfilm (id, name) VALUES ('88', 'Рай и ад');",
"INSERT INTO topfilm (id, name) VALUES ('89', 'Звёздные войны. Эпизод VI: Возвращение джедая');",
"INSERT INTO topfilm (id, name) VALUES ('90', 'Космическая одиссея 2001 года');",
"INSERT INTO topfilm (id, name) VALUES ('91', 'Вечное сияние чистого разума');",
"INSERT INTO topfilm (id, name) VALUES ('92', 'Бешеные псы');",
"INSERT INTO topfilm (id, name) VALUES ('93', 'Капернаум');",
"INSERT INTO topfilm (id, name) VALUES ('94', 'Охота');",
"INSERT INTO topfilm (id, name) VALUES ('95', 'Лоуренс Аравийский');",
"INSERT INTO topfilm (id, name) VALUES ('96', 'Гражданин Кейн');",
"INSERT INTO topfilm (id, name) VALUES ('97', 'М');",
"INSERT INTO topfilm (id, name) VALUES ('98', 'К северу через северо-запад');",
"INSERT INTO topfilm (id, name) VALUES ('99', 'Иди и смотри');",
"INSERT INTO topfilm (id, name) VALUES ('100', 'Головокружение');",
"INSERT INTO topfilm (id, name) VALUES ('101', 'Амели');",
"INSERT INTO topfilm (id, name) VALUES ('102', 'Заводной апельсин');",
"INSERT INTO topfilm (id, name) VALUES ('103', 'Двойная страховка');",
"INSERT INTO topfilm (id, name) VALUES ('104', 'Квартира');",
"INSERT INTO topfilm (id, name) VALUES ('105', 'Цельнометаллическая оболочка');",
"INSERT INTO topfilm (id, name) VALUES ('106', 'Жить');",
"INSERT INTO topfilm (id, name) VALUES ('107', 'Лицо со шрамом');",
"INSERT INTO topfilm (id, name) VALUES ('108', 'Убить пересмешника');",
"INSERT INTO topfilm (id, name) VALUES ('109', 'Афера');",
"INSERT INTO topfilm (id, name) VALUES ('110', 'Гамильтон');",
"INSERT INTO topfilm (id, name) VALUES ('111', 'Схватка');",
"INSERT INTO topfilm (id, name) VALUES ('112', 'Таксист');",
"INSERT INTO topfilm (id, name) VALUES ('113', 'Вверх');",
"INSERT INTO topfilm (id, name) VALUES ('114', 'Пожары');",
"INSERT INTO topfilm (id, name) VALUES ('115', 'Секреты Лос-Анджелеса');",
"INSERT INTO topfilm (id, name) VALUES ('116', 'Развод Надера и Симин');",
"INSERT INTO topfilm (id, name) VALUES ('117', 'Метрополис');",
"INSERT INTO topfilm (id, name) VALUES ('118', 'Крепкий орешек');",
"INSERT INTO topfilm (id, name) VALUES ('119', 'Большой куш');",
"INSERT INTO topfilm (id, name) VALUES ('120', 'Похитители велосипедов');",
"INSERT INTO topfilm (id, name) VALUES ('121', 'Индиана Джонс и последний крестовый поход');",
"INSERT INTO topfilm (id, name) VALUES ('122', '1917');",
"INSERT INTO topfilm (id, name) VALUES ('123', 'Звёздочки на земле');",
"INSERT INTO topfilm (id, name) VALUES ('124', 'Бункер');",
"INSERT INTO topfilm (id, name) VALUES ('125', 'На несколько долларов больше');",
"INSERT INTO topfilm (id, name) VALUES ('126', 'Бэтмен: Начало');",
"INSERT INTO topfilm (id, name) VALUES ('127', 'Дангал');",
"INSERT INTO topfilm (id, name) VALUES ('128', 'Малыш');",
"INSERT INTO topfilm (id, name) VALUES ('129', 'В джазе только девушки');",
"INSERT INTO topfilm (id, name) VALUES ('130', 'Всё о Еве');",
"INSERT INTO topfilm (id, name) VALUES ('131', 'Отец');",
"INSERT INTO topfilm (id, name) VALUES ('132', 'Зелёная книга');",
"INSERT INTO topfilm (id, name) VALUES ('133', 'Волк с Уолл-стрит');",
"INSERT INTO topfilm (id, name) VALUES ('134', 'Нюрнбергский процесс');",
"INSERT INTO topfilm (id, name) VALUES ('135', 'Ран');",
"INSERT INTO topfilm (id, name) VALUES ('136', 'Казино');",
"INSERT INTO topfilm (id, name) VALUES ('137', 'Непрощённый');",
"INSERT INTO topfilm (id, name) VALUES ('138', 'Лабиринт фавна');",
"INSERT INTO topfilm (id, name) VALUES ('139', 'Человек-паук: Нет пути домой');",
"INSERT INTO topfilm (id, name) VALUES ('140', 'Нефть');",
"INSERT INTO topfilm (id, name) VALUES ('141', 'Шоу Трумана');",
"INSERT INTO topfilm (id, name) VALUES ('142', 'Шестое чувство');",
"INSERT INTO topfilm (id, name) VALUES ('143', 'Игры разума');",
"INSERT INTO topfilm (id, name) VALUES ('144', 'Монти Пайтон и Священный Грааль');",
"INSERT INTO topfilm (id, name) VALUES ('145', 'Телохранитель');",
"INSERT INTO topfilm (id, name) VALUES ('146', 'Сокровища Сьерра-Мадре');",
"INSERT INTO topfilm (id, name) VALUES ('147', 'Остров проклятых');",
"INSERT INTO topfilm (id, name) VALUES ('148', 'Парк юрского периода');",
"INSERT INTO topfilm (id, name) VALUES ('149', 'Расёмон');",
"INSERT INTO topfilm (id, name) VALUES ('150', 'Большой побег');",
"INSERT INTO topfilm (id, name) VALUES ('151', 'Убить Билла. Фильм 1');",
"INSERT INTO topfilm (id, name) VALUES ('152', 'Старикам тут не место');",
"INSERT INTO topfilm (id, name) VALUES ('153', 'В поисках Немо');",
"INSERT INTO topfilm (id, name) VALUES ('154', 'Человек-слон');",
"INSERT INTO topfilm (id, name) VALUES ('155', 'Китайский квартал');",
"INSERT INTO topfilm (id, name) VALUES ('156', 'Бешеный бык');",
"INSERT INTO topfilm (id, name) VALUES ('157', 'Нечто');",
"INSERT INTO topfilm (id, name) VALUES ('158', 'Унесённые ветром');",
"INSERT INTO topfilm (id, name) VALUES ('159', 'V — значит вендетта');",
"INSERT INTO topfilm (id, name) VALUES ('160', 'Головоломка');",
"INSERT INTO topfilm (id, name) VALUES ('161', 'Карты, деньги, два ствола');",
"INSERT INTO topfilm (id, name) VALUES ('162', 'В случае убийства набирайте «М»');",
"INSERT INTO topfilm (id, name) VALUES ('163', 'Тайна в его глазах');",
"INSERT INTO topfilm (id, name) VALUES ('164', 'Ходячий замок');",
"INSERT INTO topfilm (id, name) VALUES ('165', 'Мост через реку Квай');",
"INSERT INTO topfilm (id, name) VALUES ('166', 'Три билборда на границе Эббинга, Миссури');",
"INSERT INTO topfilm (id, name) VALUES ('167', 'На игле');",
"INSERT INTO topfilm (id, name) VALUES ('168', 'Воин');",
"INSERT INTO topfilm (id, name) VALUES ('169', 'Гран Торино');",
"INSERT INTO topfilm (id, name) VALUES ('170', 'Фарго');",
"INSERT INTO topfilm (id, name) VALUES ('171', 'Пленницы');",
"INSERT INTO topfilm (id, name) VALUES ('172', 'Мой сосед Тоторо');",
"INSERT INTO topfilm (id, name) VALUES ('173', 'Малышка на миллион');",
"INSERT INTO topfilm (id, name) VALUES ('174', 'Поймай меня, если сможешь');",
"INSERT INTO topfilm (id, name) VALUES ('175', 'Золотая лихорадка');",
"INSERT INTO topfilm (id, name) VALUES ('176', 'Бегущий по лезвию');",
"INSERT INTO topfilm (id, name) VALUES ('177', 'Дети небес');",
"INSERT INTO topfilm (id, name) VALUES ('178', 'В порту');",
"INSERT INTO topfilm (id, name) VALUES ('179', 'Третий человек');",
"INSERT INTO topfilm (id, name) VALUES ('180', 'Перед рассветом');",
"INSERT INTO topfilm (id, name) VALUES ('181', '12 лет рабства');",
"INSERT INTO topfilm (id, name) VALUES ('182', 'Бен-Гур');",
"INSERT INTO topfilm (id, name) VALUES ('183', 'Земляничная поляна');",
"INSERT INTO topfilm (id, name) VALUES ('184', 'Гарри Поттер и Дары Смерти. Часть 2');",
"INSERT INTO topfilm (id, name) VALUES ('185', 'Исчезнувшая');",
"INSERT INTO topfilm (id, name) VALUES ('186', 'Генерал');",
"INSERT INTO topfilm (id, name) VALUES ('187', 'Охотник на оленей');",
"INSERT INTO topfilm (id, name) VALUES ('188', 'Во имя отца');",
"INSERT INTO topfilm (id, name) VALUES ('189', 'Отель «Гранд Будапешт»');",
"INSERT INTO topfilm (id, name) VALUES ('190', 'Барри Линдон');",
"INSERT INTO topfilm (id, name) VALUES ('191', 'Плата за страх');",
"INSERT INTO topfilm (id, name) VALUES ('192', 'Мистер Смит едет в Вашингтон');",
"INSERT INTO topfilm (id, name) VALUES ('193', 'По соображениям совести');",
"INSERT INTO topfilm (id, name) VALUES ('194', 'Шерлок-младший');",
"INSERT INTO topfilm (id, name) VALUES ('195', 'Воспоминания об убийстве');",
"INSERT INTO topfilm (id, name) VALUES ('196', 'Клаус');",
"INSERT INTO topfilm (id, name) VALUES ('197', 'Дикие истории');",
"INSERT INTO topfilm (id, name) VALUES ('198', 'Седьмая печать');",
"INSERT INTO topfilm (id, name) VALUES ('199', 'Комната');",
"INSERT INTO topfilm (id, name) VALUES ('200', 'Безумный Макс: Дорога ярости');",
"INSERT INTO topfilm (id, name) VALUES ('201', 'Как приручить дракона');",
"INSERT INTO topfilm (id, name) VALUES ('202', 'Мэри и Макс');",
"INSERT INTO topfilm (id, name) VALUES ('203', 'Большой Лебовски');",
"INSERT INTO topfilm (id, name) VALUES ('204', 'Челюсти (фильм)');",
"INSERT INTO topfilm (id, name) VALUES ('205', 'Корпорация монстров');",
"INSERT INTO topfilm (id, name) VALUES ('206', 'Токийская повесть');",
"INSERT INTO topfilm (id, name) VALUES ('207', 'Всё везде и сразу');",
"INSERT INTO topfilm (id, name) VALUES ('208', 'Общество мёртвых поэтов');",
"INSERT INTO topfilm (id, name) VALUES ('209', 'Страсти Жанны д’Арк');",
"INSERT INTO topfilm (id, name) VALUES ('210', 'Отель Руанда');",
"INSERT INTO topfilm (id, name) VALUES ('211', 'Ford против Ferrari');",
"INSERT INTO topfilm (id, name) VALUES ('212', 'Рокки');",
"INSERT INTO topfilm (id, name) VALUES ('213', 'Взвод');",
"INSERT INTO topfilm (id, name) VALUES ('214', 'Песнь дороги');",
"INSERT INTO topfilm (id, name) VALUES ('215', 'Терминатор');",
"INSERT INTO topfilm (id, name) VALUES ('216', 'Останься со мной');",
"INSERT INTO topfilm (id, name) VALUES ('217', 'В центре внимания');",
"INSERT INTO topfilm (id, name) VALUES ('218', 'Гонка');",
"INSERT INTO topfilm (id, name) VALUES ('219', 'Логан');",
"INSERT INTO topfilm (id, name) VALUES ('220', 'Рататуй ');",
"INSERT INTO topfilm (id, name) VALUES ('221', 'Телесеть');",
"INSERT INTO topfilm (id, name) VALUES ('222', 'В диких условиях');",
"INSERT INTO topfilm (id, name) VALUES ('223', 'Волшебник страны Оз ');",
"INSERT INTO topfilm (id, name) VALUES ('224', 'День сурка');",
"INSERT INTO topfilm (id, name) VALUES ('225', 'Перед закатом');",
"INSERT INTO topfilm (id, name) VALUES ('226', 'Да прольётся свет');",
"INSERT INTO topfilm (id, name) VALUES ('227', 'Изгоняющий дьявола');",
"INSERT INTO topfilm (id, name) VALUES ('228', 'Лучшие годы нашей жизни');",
"INSERT INTO topfilm (id, name) VALUES ('229', 'Суперсемейка');",
"INSERT INTO topfilm (id, name) VALUES ('230', 'Быть или не быть');",
"INSERT INTO topfilm (id, name) VALUES ('231', 'Битва за Алжир');",
"INSERT INTO topfilm (id, name) VALUES ('232', 'Гроздья гнева');",
"INSERT INTO topfilm (id, name) VALUES ('233', 'Ребекка');",
"INSERT INTO topfilm (id, name) VALUES ('234', 'Хатико: Самый верный друг');",
"INSERT INTO topfilm (id, name) VALUES ('235', 'Пираты Карибского моря: Проклятие Чёрной жемчужины');",
"INSERT INTO topfilm (id, name) VALUES ('236', 'Хладнокровный Люк');",
"INSERT INTO topfilm (id, name) VALUES ('237', 'Сука любовь');",
"INSERT INTO topfilm (id, name) VALUES ('238', 'Ненависть');",
"INSERT INTO topfilm (id, name) VALUES ('239', 'Мой отец и мой сын');",
"INSERT INTO topfilm (id, name) VALUES ('240', 'Четыреста ударов');",
"INSERT INTO topfilm (id, name) VALUES ('241', 'Персона');",
"INSERT INTO topfilm (id, name) VALUES ('242', 'Это случилось однажды ночью');",
"INSERT INTO topfilm (id, name) VALUES ('243', 'Звуки музыки');",
"INSERT INTO topfilm (id, name) VALUES ('244', 'Житие Брайана по Монти Пайтону');",
"INSERT INTO topfilm (id, name) VALUES ('245', 'Служанка');",
"INSERT INTO topfilm (id, name) VALUES ('246', 'Дерсу Узала');",
"INSERT INTO topfilm (id, name) VALUES ('247', 'Аладдин');",
"INSERT INTO topfilm (id, name) VALUES ('248', 'Ганди');",
"INSERT INTO topfilm (id, name) VALUES ('249', 'Прислуга');",
"INSERT INTO topfilm (id, name) VALUES ('250', 'Стальной гигант');"]
        for sql_command in sql_commands:
            cursor.execute(sql_command)

def fill_trivia(db):
    db.autocommit = True
    with db.cursor() as cursor:
        sql_commands = ["INSERT INTO trivia (id, year, genre, country) VALUES ('1', '1994', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('2', '1972', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('3', '2008', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('4', '1974', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('5', '1957', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('6', '1993', 'драма', 'Новая Зеландия');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('7', '2003', 'фэнтези', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('8', '1994', 'чёрная комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('9', '2001', 'фэнтези', 'Новая Зеландия');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('10', '1966', 'приключение', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('11', '1994', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('12', '1999', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('13', '2010', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('14', '2002', 'фэнтези', 'Новая Зеландия');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('15', '1980', 'научная фантастика', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('16', '1999', 'научная фантастика', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('17', '1990', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('18', '1975', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('19', '1995', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('20', '1954', 'приключение', 'Япония');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('21', '1946', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('22', '1991', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('23', '2002', 'детектив', 'Бразилия');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('24', '1998', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('25', '1997', 'драма', 'Италия');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('26', '1999', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('27', '2014', 'приключение', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('28', '1977', 'научная фантастика', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('29', '1991', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('30', '1985', 'научная фантастика', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('31', '2001', 'аниме', 'Япония');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('32', '1960', 'фильм ужасов', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('33', '2002', 'биография', 'Франция');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('34', '1994', 'детектив', 'Франция');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('35', '2019', 'комедия', 'Южная Корея');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('36', '1994', 'мультфильм', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('37', '2000', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('38', '1998', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('39', '2006', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('40', '1995', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('41', '2006', 'фэнтези', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('42', '1942', 'мелодрама', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('43', '2014', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('44', '2011', 'трагикомедия', 'Франция');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('45', '1988', 'мультфильм', 'Япония');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('46', '1962', 'боевик', 'Япония');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('47', '1936', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('48', '1968', 'вестерн', 'Италия');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('49', '1954', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('50', '1979', 'фильм ужасов', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('51', '1931', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('52', '1988', 'комедия', 'Италия');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('53', '1979', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('54', '2000', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('55', '1981', 'приключение', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('56', '2012', 'приключение', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('57', '2008', 'мультфильм', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('58', '2006', 'драма', 'Германия');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('59', '1950', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('60', '1957', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('61', '1980', 'фильм ужасов', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('62', '1940', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('63', '2018', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('64', '1957', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('65', '1986', 'фильм ужасов', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('66', '1999', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('67', '2018', 'мультфильм', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('68', '1964', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('69', '2022', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('70', '2012', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('71', '2003', 'драма', 'Южная Корея');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('72', '2019', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('73', '1984', 'биография', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('74', '1995', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('75', '1995', 'мультфильм', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('76', '2017', 'мультфильм', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('77', '2009', 'военный фильм', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('78', '1981', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('79', '2019', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('80', '1997', 'мультфильм', 'Япония');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('81', '1984', 'гангстерский фильм', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('82', '1997', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('83', '2016', 'мультфильм', 'Япония');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('84', '2000', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('85', '2010', 'мультфильм', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('86', '1952', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('87', '2009', 'комедия', 'Индия');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('88', '1963', 'детектив', 'Япония');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('89', '1983', 'научная фантастика', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('90', '1968', 'Кинофантастика', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('91', '2004', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('92', '1992', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('93', '2018', 'драма', 'Ливан');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('94', '2012', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('95', '1962', 'приключение', 'Великобритания');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('96', '1941', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('97', '1931', 'триллер', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('98', '1959', 'приключение', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('99', '1985', 'драма', 'СССР');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('100', '1958', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('101', '2001', 'комедия', 'Франция');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('102', '1971', 'научная фантастика', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('103', '1944', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('104', '1960', 'мелодрама', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('105', '1987', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('106', '1952', 'драма', 'Япония');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('107', '1983', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('108', '1962', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('109', '1973', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('110', '2020', 'биография', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('111', '1995', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('112', '1976', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('113', '2009', 'мультфильм', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('114', '2010', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('115', '1997', 'триллер', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('116', '2011', 'драма', 'Иран');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('117', '1927', 'научная фантастика', 'Германия');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('118', '1988', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('119', '2000', 'детектив', 'Великобритания');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('120', '1948', 'детектив', 'Италия');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('121', '1989', 'приключение', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('122', '2019', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('123', '2007', 'драма', 'Индия');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('124', '2004', 'биография', 'Испания');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('125', '1965', 'вестерн', 'Италия');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('126', '2005', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('127', '2016', 'боевик', 'Индия');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('128', '1921', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('129', '1959', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('130', '1950', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('131', '2020', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('132', '2018', 'биография', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('133', '2013', 'биография', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('134', '1961', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('135', '1985', 'боевик', 'Япония');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('136', '1995', 'биография', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('137', '1992', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('138', '2006', 'фэнтези', 'Мексика');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('139', '2021', 'научная фантастика', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('140', '2007', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('141', '1998', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('142', '1999', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('143', '2001', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('144', '1975', 'приключение', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('145', '1961', 'боевик', 'Япония');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('146', '1948', 'приключение', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('147', '2010', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('148', '1993', 'приключение', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('149', '1950', 'драма', 'Япония');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('150', '1963', 'приключение', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('151', '2003', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('152', '2007', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('153', '2003', 'мультфильм', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('154', '1980', 'биография', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('155', '1974', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('156', '1980', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('157', '1982', 'научная фантастика', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('158', '1939', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('159', '2006', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('160', '2015', 'мультфильм', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('161', '1998', 'детектив', 'Великобритания');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('162', '1954', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('163', '2009', 'драма', 'Аргентина');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('164', '2004', 'аниме', 'Япония');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('165', '1957', 'приключение', 'Великобритания');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('166', '2017', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('167', '1996', 'детектив', 'Великобритания');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('168', '2011', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('169', '2008', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('170', '1996', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('171', '2013', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('172', '1988', 'мультфильм', 'Япония');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('173', '2004', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('174', '2002', 'биография', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('175', '1925', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('176', '1982', 'научная фантастика', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('177', '1997', 'драма', 'Иран');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('178', '1954', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('179', '1949', 'нуар', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('180', '1995', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('181', '2013', 'биография', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('182', '1959', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('183', '1957', 'драма', 'Швеция');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('184', '2011', 'фэнтези', 'Великобритания');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('185', '2014', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('186', '1927', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('187', '1978', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('188', '1993', 'биография', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('189', '2014', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('190', '1975', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('191', '1953', 'приключение', 'Франция');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('192', '1939', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('193', '2016', 'биография', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('194', '1924', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('195', '2003', 'драма', 'Южная Корея');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('196', '2019', 'мультфильм', 'Испания');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('197', '2014', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('198', '1957', 'драма', 'Швеция');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('199', '2015', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('200', '2015', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('201', '2010', 'мультфильм', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('202', '2009', 'приключение', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('203', '1998', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('204', '1975', 'фильм ужасов', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('205', '2001', 'мультфильм', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('206', '1953', 'драма', 'Япония');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('207', '2022', 'чёрная комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('208', '1989', 'Комедийная драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('209', '1928', 'биография', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('210', '2004', 'биография', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('211', '2019', 'фильм о спорте', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('212', '1976', 'фильм о спорте', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('213', '1986', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('214', '1955', 'драма', 'Индия');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('215', '1984', 'фэнтези', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('216', '1986', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('217', '2015', 'биография', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('218', '2013', 'фильм-биография', 'Великобритания');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('219', '2017', 'боевик', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('220', '2007', 'мультфильм', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('221', '1975', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('222', '2007', 'приключение', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('223', '1939', 'приключения', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('224', '1993', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('225', '2004', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('226', '2021', 'драма', 'Индия');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('227', '1973', 'фильм ужасов', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('228', '1946', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('229', '2004', 'приключения', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('230', '1942', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('231', '1966', 'драма', 'Алжир');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('232', '1940', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('233', '1940', 'мистический фильм', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('234', '2009', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('235', '2003', 'экшн', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('236', '1967', 'детектив', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('237', '2000', 'драма', 'Мексика');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('238', '1995', 'драма', 'Франция');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('239', '2005', 'драма', 'Турция');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('240', '1959', 'драма', 'Франция');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('241', '1966', 'драма', 'Швеция');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('242', '1934', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('243', '1965', 'мюзикл', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('244', '1979', 'комедия', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('245', '2016', 'драма', 'Южная Корея');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('246', '1975', 'драма', 'Япония');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('247', '1992', 'мюзикл', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('248', '1982', 'драма', 'Великобритания');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('249', '2011', 'драма', 'США');",
"INSERT INTO trivia (id, year, genre, country) VALUES ('250', '1999', 'фантастика', 'США');"]
        for sql_command in sql_commands:
            cursor.execute(sql_command)

def fill_scores(db):
    db.autocommit = True
    with db.cursor() as cursor:
        sql_commands = ["INSERT INTO scores (id, rating) VALUES ('1', '9.2');",
"INSERT INTO scores (id, rating) VALUES ('2', '9.2');",
"INSERT INTO scores (id, rating) VALUES ('3', '9');",
"INSERT INTO scores (id, rating) VALUES ('4', '9');",
"INSERT INTO scores (id, rating) VALUES ('5', '9');",
"INSERT INTO scores (id, rating) VALUES ('6', '8.9');",
"INSERT INTO scores (id, rating) VALUES ('7', '8.9');",
"INSERT INTO scores (id, rating) VALUES ('8', '8.8');",
"INSERT INTO scores (id, rating) VALUES ('9', '8.8');",
"INSERT INTO scores (id, rating) VALUES ('10', '8.8');",
"INSERT INTO scores (id, rating) VALUES ('11', '8.8');",
"INSERT INTO scores (id, rating) VALUES ('12', '8.7');",
"INSERT INTO scores (id, rating) VALUES ('13', '8.7');",
"INSERT INTO scores (id, rating) VALUES ('14', '8.7');",
"INSERT INTO scores (id, rating) VALUES ('15', '8.7');",
"INSERT INTO scores (id, rating) VALUES ('16', '8.7');",
"INSERT INTO scores (id, rating) VALUES ('17', '8.7');",
"INSERT INTO scores (id, rating) VALUES ('18', '8.6');",
"INSERT INTO scores (id, rating) VALUES ('19', '8.6');",
"INSERT INTO scores (id, rating) VALUES ('20', '8.6');",
"INSERT INTO scores (id, rating) VALUES ('21', '8.6');",
"INSERT INTO scores (id, rating) VALUES ('22', '8.6');",
"INSERT INTO scores (id, rating) VALUES ('23', '8.6');",
"INSERT INTO scores (id, rating) VALUES ('24', '8.6');",
"INSERT INTO scores (id, rating) VALUES ('25', '8.6');",
"INSERT INTO scores (id, rating) VALUES ('26', '8.6');",
"INSERT INTO scores (id, rating) VALUES ('27', '8.6');",
"INSERT INTO scores (id, rating) VALUES ('28', '8.6');",
"INSERT INTO scores (id, rating) VALUES ('29', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('30', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('31', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('32', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('33', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('34', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('35', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('36', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('37', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('38', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('39', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('40', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('41', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('42', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('43', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('44', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('45', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('46', '8.5');",
"INSERT INTO scores (id, rating) VALUES ('47', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('48', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('49', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('50', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('51', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('52', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('53', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('54', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('55', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('56', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('57', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('58', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('59', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('60', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('61', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('62', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('63', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('64', '8.4');",
"INSERT INTO scores (id, rating) VALUES ('65', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('66', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('67', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('68', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('69', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('70', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('71', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('72', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('73', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('74', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('75', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('76', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('77', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('78', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('79', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('80', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('81', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('82', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('83', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('84', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('85', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('86', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('87', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('88', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('89', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('90', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('91', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('92', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('93', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('94', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('95', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('96', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('97', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('98', '8.3');",
"INSERT INTO scores (id, rating) VALUES ('99', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('100', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('101', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('102', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('103', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('104', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('105', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('106', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('107', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('108', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('109', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('110', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('111', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('112', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('113', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('114', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('115', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('116', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('117', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('118', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('119', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('120', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('121', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('122', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('123', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('124', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('125', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('126', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('127', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('128', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('129', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('130', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('131', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('132', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('133', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('134', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('135', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('136', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('137', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('138', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('139', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('140', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('141', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('142', '8.2');",
"INSERT INTO scores (id, rating) VALUES ('143', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('144', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('145', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('146', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('147', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('148', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('149', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('150', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('151', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('152', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('153', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('154', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('155', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('156', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('157', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('158', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('159', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('160', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('161', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('162', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('163', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('164', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('165', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('166', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('167', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('168', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('169', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('170', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('171', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('172', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('173', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('174', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('175', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('176', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('177', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('178', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('179', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('180', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('181', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('182', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('183', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('184', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('185', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('186', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('187', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('188', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('189', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('190', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('191', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('192', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('193', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('194', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('195', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('196', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('197', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('198', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('199', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('200', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('201', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('202', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('203', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('204', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('205', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('206', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('207', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('208', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('209', '8.1');",
"INSERT INTO scores (id, rating) VALUES ('210', '8');",
"INSERT INTO scores (id, rating) VALUES ('211', '8');",
"INSERT INTO scores (id, rating) VALUES ('212', '8');",
"INSERT INTO scores (id, rating) VALUES ('213', '8');",
"INSERT INTO scores (id, rating) VALUES ('214', '8');",
"INSERT INTO scores (id, rating) VALUES ('215', '8');",
"INSERT INTO scores (id, rating) VALUES ('216', '8');",
"INSERT INTO scores (id, rating) VALUES ('217', '8');",
"INSERT INTO scores (id, rating) VALUES ('218', '8');",
"INSERT INTO scores (id, rating) VALUES ('219', '8');",
"INSERT INTO scores (id, rating) VALUES ('220', '8');",
"INSERT INTO scores (id, rating) VALUES ('221', '8');",
"INSERT INTO scores (id, rating) VALUES ('222', '8');",
"INSERT INTO scores (id, rating) VALUES ('223', '8');",
"INSERT INTO scores (id, rating) VALUES ('224', '8');",
"INSERT INTO scores (id, rating) VALUES ('225', '8');",
"INSERT INTO scores (id, rating) VALUES ('226', '8');",
"INSERT INTO scores (id, rating) VALUES ('227', '8');",
"INSERT INTO scores (id, rating) VALUES ('228', '8');",
"INSERT INTO scores (id, rating) VALUES ('229', '8');",
"INSERT INTO scores (id, rating) VALUES ('230', '8');",
"INSERT INTO scores (id, rating) VALUES ('231', '8');",
"INSERT INTO scores (id, rating) VALUES ('232', '8');",
"INSERT INTO scores (id, rating) VALUES ('233', '8');",
"INSERT INTO scores (id, rating) VALUES ('234', '8');",
"INSERT INTO scores (id, rating) VALUES ('235', '8');",
"INSERT INTO scores (id, rating) VALUES ('236', '8');",
"INSERT INTO scores (id, rating) VALUES ('237', '8');",
"INSERT INTO scores (id, rating) VALUES ('238', '8');",
"INSERT INTO scores (id, rating) VALUES ('239', '8');",
"INSERT INTO scores (id, rating) VALUES ('240', '8');",
"INSERT INTO scores (id, rating) VALUES ('241', '8');",
"INSERT INTO scores (id, rating) VALUES ('242', '8');",
"INSERT INTO scores (id, rating) VALUES ('243', '8');",
"INSERT INTO scores (id, rating) VALUES ('244', '8');",
"INSERT INTO scores (id, rating) VALUES ('245', '8');",
"INSERT INTO scores (id, rating) VALUES ('246', '8');",
"INSERT INTO scores (id, rating) VALUES ('247', '8');",
"INSERT INTO scores (id, rating) VALUES ('248', '8');",
"INSERT INTO scores (id, rating) VALUES ('249', '8');",
"INSERT INTO scores (id, rating) VALUES ('250', '8');"]
        for sql_command in sql_commands:
            cursor.execute(sql_command)


def fill_authors(db):
    db.autocommit = True
    with db.cursor() as cursor:
        sql_commands = ["INSERT INTO authors (id, director) VALUES ('1', 'Фрэнк Дарабонт');",
"INSERT INTO authors (id, director) VALUES ('2', 'Фрэнсис Форд Коппола');",
"INSERT INTO authors (id, director) VALUES ('3', 'Кристофер Нолан');",
"INSERT INTO authors (id, director) VALUES ('4', 'Фрэнсис Форд Коппола');",
"INSERT INTO authors (id, director) VALUES ('5', 'Сидни Люмет');",
"INSERT INTO authors (id, director) VALUES ('6', 'Стивен Спилберг');",
"INSERT INTO authors (id, director) VALUES ('7', 'Питер Джексон');",
"INSERT INTO authors (id, director) VALUES ('8', 'Квентин Тарантино');",
"INSERT INTO authors (id, director) VALUES ('9', 'Питер Джексон');",
"INSERT INTO authors (id, director) VALUES ('10', 'Серджо Леоне');",
"INSERT INTO authors (id, director) VALUES ('11', 'Роберт Земекис');",
"INSERT INTO authors (id, director) VALUES ('12', 'Дэвид Финчер');",
"INSERT INTO authors (id, director) VALUES ('13', 'Кристофер Нолан');",
"INSERT INTO authors (id, director) VALUES ('14', 'Питер Джексон');",
"INSERT INTO authors (id, director) VALUES ('15', 'Ирвин Кершнер');",
"INSERT INTO authors (id, director) VALUES ('16', 'Энди и Ларри Вачовски');",
"INSERT INTO authors (id, director) VALUES ('17', 'Мартин Скорсезе');",
"INSERT INTO authors (id, director) VALUES ('18', 'Милош Форман');",
"INSERT INTO authors (id, director) VALUES ('19', 'Дэвид Финчер');",
"INSERT INTO authors (id, director) VALUES ('20', 'Акира Куросава');",
"INSERT INTO authors (id, director) VALUES ('21', 'Фрэнк Капра');",
"INSERT INTO authors (id, director) VALUES ('22', 'Джонатан Демми');",
"INSERT INTO authors (id, director) VALUES ('23', 'Фернанду Мейреллиш');",
"INSERT INTO authors (id, director) VALUES ('24', 'Стивен Спилберг');",
"INSERT INTO authors (id, director) VALUES ('25', 'Роберто Бениньи');",
"INSERT INTO authors (id, director) VALUES ('26', 'Фрэнк Дарабонт');",
"INSERT INTO authors (id, director) VALUES ('27', 'Кристофер Нолан');",
"INSERT INTO authors (id, director) VALUES ('28', 'Джордж Лукас');",
"INSERT INTO authors (id, director) VALUES ('29', 'Джеймс Кэмерон');",
"INSERT INTO authors (id, director) VALUES ('30', 'Роберт Земекис');",
"INSERT INTO authors (id, director) VALUES ('31', 'Хаяо Миядзаки');",
"INSERT INTO authors (id, director) VALUES ('32', 'Альфред Хичкок');",
"INSERT INTO authors (id, director) VALUES ('33', 'Роман Полански');",
"INSERT INTO authors (id, director) VALUES ('34', 'Люк Бессон');",
"INSERT INTO authors (id, director) VALUES ('35', 'Пон Чжун Хо');",
"INSERT INTO authors (id, director) VALUES ('36', 'Роджер Аллерс');",
"INSERT INTO authors (id, director) VALUES ('37', 'Ридли Скотт');",
"INSERT INTO authors (id, director) VALUES ('38', 'Тони Кэй');",
"INSERT INTO authors (id, director) VALUES ('39', 'Мартин Скорсезе');",
"INSERT INTO authors (id, director) VALUES ('40', 'Брайан Сингер');",
"INSERT INTO authors (id, director) VALUES ('41', 'Кристофер Нолан');",
"INSERT INTO authors (id, director) VALUES ('42', 'Майкл Кёртиц');",
"INSERT INTO authors (id, director) VALUES ('43', 'Дамьен Шазель');",
"INSERT INTO authors (id, director) VALUES ('44', 'Оливье Накаш, Эрик Толедано');",
"INSERT INTO authors (id, director) VALUES ('45', 'Исао Такахата');",
"INSERT INTO authors (id, director) VALUES ('46', 'Масаки Кобаяси');",
"INSERT INTO authors (id, director) VALUES ('47', 'Чарли Чаплин');",
"INSERT INTO authors (id, director) VALUES ('48', 'Серджо Леоне');",
"INSERT INTO authors (id, director) VALUES ('49', 'Альфред Хичкок');",
"INSERT INTO authors (id, director) VALUES ('50', 'Ридли Скотт');",
"INSERT INTO authors (id, director) VALUES ('51', 'Чарли Чаплин');",
"INSERT INTO authors (id, director) VALUES ('52', 'Джузеппе Торнаторе');",
"INSERT INTO authors (id, director) VALUES ('53', 'Фрэнсис Форд Коппола');",
"INSERT INTO authors (id, director) VALUES ('54', 'Кристофер Нолан');",
"INSERT INTO authors (id, director) VALUES ('55', 'Стивен Спилберг');",
"INSERT INTO authors (id, director) VALUES ('56', 'Квентин Тарантино');",
"INSERT INTO authors (id, director) VALUES ('57', 'Эндрю Стэнтон');",
"INSERT INTO authors (id, director) VALUES ('58', 'Флориан Хенкель фон Доннерсмарк');",
"INSERT INTO authors (id, director) VALUES ('59', 'Билли Уайлдер');",
"INSERT INTO authors (id, director) VALUES ('60', 'Стэнли Кубрик');",
"INSERT INTO authors (id, director) VALUES ('61', 'Стэнли Кубрик');",
"INSERT INTO authors (id, director) VALUES ('62', 'Чарли Чаплин');",
"INSERT INTO authors (id, director) VALUES ('63', 'Братья Руссо');",
"INSERT INTO authors (id, director) VALUES ('64', 'Билли Уайлдер');",
"INSERT INTO authors (id, director) VALUES ('65', 'Джеймс Кэмерон');",
"INSERT INTO authors (id, director) VALUES ('66', 'Сэм Мендес');",
"INSERT INTO authors (id, director) VALUES ('67', 'Боб Персичетти');",
"INSERT INTO authors (id, director) VALUES ('68', 'Стэнли Кубрик');",
"INSERT INTO authors (id, director) VALUES ('69', 'Джозеф Косински');",
"INSERT INTO authors (id, director) VALUES ('70', 'Кристофер Нолан');",
"INSERT INTO authors (id, director) VALUES ('71', 'Пак Чхан Ук');",
"INSERT INTO authors (id, director) VALUES ('72', 'Тодд Филлипс');",
"INSERT INTO authors (id, director) VALUES ('73', 'Милош Форман');",
"INSERT INTO authors (id, director) VALUES ('74', 'Мел Гибсон');",
"INSERT INTO authors (id, director) VALUES ('75', 'Джон Лассетер');",
"INSERT INTO authors (id, director) VALUES ('76', 'Ли Анкрич');",
"INSERT INTO authors (id, director) VALUES ('77', 'Квентин Тарантино');",
"INSERT INTO authors (id, director) VALUES ('78', 'Вольфганг Петерсен');",
"INSERT INTO authors (id, director) VALUES ('79', 'Братья Руссо');",
"INSERT INTO authors (id, director) VALUES ('80', 'Хаяо Миядзаки');",
"INSERT INTO authors (id, director) VALUES ('81', 'Серджио Леоне');",
"INSERT INTO authors (id, director) VALUES ('82', 'Гас Ван Сент');",
"INSERT INTO authors (id, director) VALUES ('83', 'Макото Синкай');",
"INSERT INTO authors (id, director) VALUES ('84', 'Даррен Аронофски');",
"INSERT INTO authors (id, director) VALUES ('85', 'Ли Анкрич');",
"INSERT INTO authors (id, director) VALUES ('86', 'Стэнли Донен');",
"INSERT INTO authors (id, director) VALUES ('87', 'Раджкумар Хирани');",
"INSERT INTO authors (id, director) VALUES ('88', 'Акира Куросава');",
"INSERT INTO authors (id, director) VALUES ('89', 'Ричард Маркуанд');",
"INSERT INTO authors (id, director) VALUES ('90', 'Стэнли Кубрик');",
"INSERT INTO authors (id, director) VALUES ('91', 'Мишель Гондри');",
"INSERT INTO authors (id, director) VALUES ('92', 'Квентин Тарантино');",
"INSERT INTO authors (id, director) VALUES ('93', 'Надин Лабаки');",
"INSERT INTO authors (id, director) VALUES ('94', 'Томас Винтерберг');",
"INSERT INTO authors (id, director) VALUES ('95', 'Дэвид Лин');",
"INSERT INTO authors (id, director) VALUES ('96', 'Орсон Уэллс');",
"INSERT INTO authors (id, director) VALUES ('97', 'Фриц Ланг');",
"INSERT INTO authors (id, director) VALUES ('98', 'Альфред Хичкок');",
"INSERT INTO authors (id, director) VALUES ('99', 'Элем Климов');",
"INSERT INTO authors (id, director) VALUES ('100', 'Альфред Хичкок');",
"INSERT INTO authors (id, director) VALUES ('101', 'Жан-Пьер Жене');",
"INSERT INTO authors (id, director) VALUES ('102', 'Стэнли Кубрик');",
"INSERT INTO authors (id, director) VALUES ('103', 'Билли Уайлдер');",
"INSERT INTO authors (id, director) VALUES ('104', 'Билли Уайлдер');",
"INSERT INTO authors (id, director) VALUES ('105', 'Стэнли Кубрик');",
"INSERT INTO authors (id, director) VALUES ('106', 'Акира Куросава');",
"INSERT INTO authors (id, director) VALUES ('107', 'Брайан де Пальма');",
"INSERT INTO authors (id, director) VALUES ('108', 'Роберт Маллиган');",
"INSERT INTO authors (id, director) VALUES ('109', 'Джордж Рой Хилл');",
"INSERT INTO authors (id, director) VALUES ('110', 'Томас Кейл');",
"INSERT INTO authors (id, director) VALUES ('111', 'Майкл Манн');",
"INSERT INTO authors (id, director) VALUES ('112', 'Мартин Скорсезе');",
"INSERT INTO authors (id, director) VALUES ('113', 'Пит Доктер');",
"INSERT INTO authors (id, director) VALUES ('114', 'Дени Вильнёв');",
"INSERT INTO authors (id, director) VALUES ('115', 'Кёртис Хэнсон');",
"INSERT INTO authors (id, director) VALUES ('116', 'Асгар Фархади');",
"INSERT INTO authors (id, director) VALUES ('117', 'Фриц Ланг');",
"INSERT INTO authors (id, director) VALUES ('118', 'Джон Мактирнан');",
"INSERT INTO authors (id, director) VALUES ('119', 'Гай Ричи');",
"INSERT INTO authors (id, director) VALUES ('120', 'Витторио де Сика');",
"INSERT INTO authors (id, director) VALUES ('121', 'Стивен Спилберг');",
"INSERT INTO authors (id, director) VALUES ('122', 'Сэм Мендес');",
"INSERT INTO authors (id, director) VALUES ('123', 'Аамир Хан');",
"INSERT INTO authors (id, director) VALUES ('124', 'Оливер Хиршбигель');",
"INSERT INTO authors (id, director) VALUES ('125', 'Серджо Леоне');",
"INSERT INTO authors (id, director) VALUES ('126', 'Кристофер Нолан');",
"INSERT INTO authors (id, director) VALUES ('127', 'Нитеш Тивари');",
"INSERT INTO authors (id, director) VALUES ('128', 'Чарли Чаплин');",
"INSERT INTO authors (id, director) VALUES ('129', 'Билли Уайлдер');",
"INSERT INTO authors (id, director) VALUES ('130', 'Джозеф Лео Манкевич');",
"INSERT INTO authors (id, director) VALUES ('131', 'Флориан Зеллер');",
"INSERT INTO authors (id, director) VALUES ('132', 'Питер Фаррелли');",
"INSERT INTO authors (id, director) VALUES ('133', 'Мартин Скорсезе');",
"INSERT INTO authors (id, director) VALUES ('134', 'Стэнли Крамер');",
"INSERT INTO authors (id, director) VALUES ('135', 'Акира Куросава');",
"INSERT INTO authors (id, director) VALUES ('136', 'Мартин Скорсезе');",
"INSERT INTO authors (id, director) VALUES ('137', 'Клинт Иствуд');",
"INSERT INTO authors (id, director) VALUES ('138', 'Гильермо дель Торо');",
"INSERT INTO authors (id, director) VALUES ('139', 'Джон Уоттс');",
"INSERT INTO authors (id, director) VALUES ('140', 'Пол Томас Андерсон');",
"INSERT INTO authors (id, director) VALUES ('141', 'Питер Уир');",
"INSERT INTO authors (id, director) VALUES ('142', 'М. Найт Шьямалан');",
"INSERT INTO authors (id, director) VALUES ('143', 'Рон Ховард');",
"INSERT INTO authors (id, director) VALUES ('144', 'Терри Гиллиам');",
"INSERT INTO authors (id, director) VALUES ('145', 'Акира Куросава');",
"INSERT INTO authors (id, director) VALUES ('146', 'Джон Хьюстон');",
"INSERT INTO authors (id, director) VALUES ('147', 'Мартин Скорсезе');",
"INSERT INTO authors (id, director) VALUES ('148', 'Стивен Спилберг');",
"INSERT INTO authors (id, director) VALUES ('149', 'Акира Куросава');",
"INSERT INTO authors (id, director) VALUES ('150', 'Джон Стёрджес');",
"INSERT INTO authors (id, director) VALUES ('151', 'Квентин Тарантино');",
"INSERT INTO authors (id, director) VALUES ('152', 'Братья Коэн');",
"INSERT INTO authors (id, director) VALUES ('153', 'Эндрю Стэнтон');",
"INSERT INTO authors (id, director) VALUES ('154', 'Дэвид Линч');",
"INSERT INTO authors (id, director) VALUES ('155', 'Роман Полански');",
"INSERT INTO authors (id, director) VALUES ('156', 'Мартин Скорсезе');",
"INSERT INTO authors (id, director) VALUES ('157', 'Джон Карпентер');",
"INSERT INTO authors (id, director) VALUES ('158', 'Виктор Флеминг');",
"INSERT INTO authors (id, director) VALUES ('159', 'Джеймс Мактиг');",
"INSERT INTO authors (id, director) VALUES ('160', 'Пит Доктер');",
"INSERT INTO authors (id, director) VALUES ('161', 'Гай Ричи');",
"INSERT INTO authors (id, director) VALUES ('162', 'Альфред Хичкок');",
"INSERT INTO authors (id, director) VALUES ('163', 'Хуан Хосе Кампанелья');",
"INSERT INTO authors (id, director) VALUES ('164', 'Хаяо Миядзаки');",
"INSERT INTO authors (id, director) VALUES ('165', 'Дэвид Лин');",
"INSERT INTO authors (id, director) VALUES ('166', 'Мартин Макдонах');",
"INSERT INTO authors (id, director) VALUES ('167', 'Дэнни Бойл');",
"INSERT INTO authors (id, director) VALUES ('168', 'Гэвин О’Коннор');",
"INSERT INTO authors (id, director) VALUES ('169', 'Клинт Иствуд');",
"INSERT INTO authors (id, director) VALUES ('170', 'Братья Коэн');",
"INSERT INTO authors (id, director) VALUES ('171', 'Дени Вильнёв');",
"INSERT INTO authors (id, director) VALUES ('172', 'Хаяо Миядзаки');",
"INSERT INTO authors (id, director) VALUES ('173', 'Клинт Иствуд');",
"INSERT INTO authors (id, director) VALUES ('174', 'Стивен Спилберг');",
"INSERT INTO authors (id, director) VALUES ('175', 'Чарли Чаплин');",
"INSERT INTO authors (id, director) VALUES ('176', 'Ридли Скотт');",
"INSERT INTO authors (id, director) VALUES ('177', 'Маджид Маджиди');",
"INSERT INTO authors (id, director) VALUES ('178', 'Элиа Казан');",
"INSERT INTO authors (id, director) VALUES ('179', 'Кэрол Рид');",
"INSERT INTO authors (id, director) VALUES ('180', 'Ричард Линклейтер');",
"INSERT INTO authors (id, director) VALUES ('181', 'Стив Маккуин');",
"INSERT INTO authors (id, director) VALUES ('182', 'Уильям Уайлер');",
"INSERT INTO authors (id, director) VALUES ('183', 'Ингмар Бергман');",
"INSERT INTO authors (id, director) VALUES ('184', 'Дэвид Йейтс');",
"INSERT INTO authors (id, director) VALUES ('185', 'Дэвид Финчер');",
"INSERT INTO authors (id, director) VALUES ('186', 'Клайд Брукман');",
"INSERT INTO authors (id, director) VALUES ('187', 'Майкл Чимино');",
"INSERT INTO authors (id, director) VALUES ('188', 'Джим Шеридан');",
"INSERT INTO authors (id, director) VALUES ('189', 'Уэс Андерсон');",
"INSERT INTO authors (id, director) VALUES ('190', 'Стэнли Кубрик');",
"INSERT INTO authors (id, director) VALUES ('191', 'Анри-Жорж Клузо');",
"INSERT INTO authors (id, director) VALUES ('192', 'Фрэнк Капра');",
"INSERT INTO authors (id, director) VALUES ('193', 'Мел Гибсон');",
"INSERT INTO authors (id, director) VALUES ('194', 'Бастер Китон');",
"INSERT INTO authors (id, director) VALUES ('195', 'Пон Чжун Хо');",
"INSERT INTO authors (id, director) VALUES ('196', 'Серхио Паблос');",
"INSERT INTO authors (id, director) VALUES ('197', 'Дамиан Шифрон');",
"INSERT INTO authors (id, director) VALUES ('198', 'Ингмар Бергман');",
"INSERT INTO authors (id, director) VALUES ('199', 'Ленни Абрахамсон');",
"INSERT INTO authors (id, director) VALUES ('200', 'Джордж Миллер');",
"INSERT INTO authors (id, director) VALUES ('201', 'Крис Сандерс');",
"INSERT INTO authors (id, director) VALUES ('202', 'Адам Эллиот');",
"INSERT INTO authors (id, director) VALUES ('203', 'Братья Коэн');",
"INSERT INTO authors (id, director) VALUES ('204', 'Стивен Спилберг');",
"INSERT INTO authors (id, director) VALUES ('205', 'Пит Доктер');",
"INSERT INTO authors (id, director) VALUES ('206', 'Ясудзиро Одзу');",
"INSERT INTO authors (id, director) VALUES ('207', 'Дэн Кван');",
"INSERT INTO authors (id, director) VALUES ('208', 'Питер Уир');",
"INSERT INTO authors (id, director) VALUES ('209', 'Карл Теодор Дрейер');",
"INSERT INTO authors (id, director) VALUES ('210', 'Терри Джордж');",
"INSERT INTO authors (id, director) VALUES ('211', 'Джеймс Мэнголд');",
"INSERT INTO authors (id, director) VALUES ('212', 'Джон Эвилдсен');",
"INSERT INTO authors (id, director) VALUES ('213', 'Оливер Стоун');",
"INSERT INTO authors (id, director) VALUES ('214', 'Сатьяджит Рай');",
"INSERT INTO authors (id, director) VALUES ('215', 'Джеймс Кэмерон');",
"INSERT INTO authors (id, director) VALUES ('216', 'Роб Райнер');",
"INSERT INTO authors (id, director) VALUES ('217', 'Томас Маккарти');",
"INSERT INTO authors (id, director) VALUES ('218', 'Рон Ховард');",
"INSERT INTO authors (id, director) VALUES ('219', 'Джеймс Мэнголд');",
"INSERT INTO authors (id, director) VALUES ('220', 'Брэд Бёрд');",
"INSERT INTO authors (id, director) VALUES ('221', 'Сидни Люмет');",
"INSERT INTO authors (id, director) VALUES ('222', 'Шон Пенн');",
"INSERT INTO authors (id, director) VALUES ('223', 'Виктор Флеминг');",
"INSERT INTO authors (id, director) VALUES ('224', 'Гарольд Рамис');",
"INSERT INTO authors (id, director) VALUES ('225', 'Ричард Линклейтер');",
"INSERT INTO authors (id, director) VALUES ('226', 'TJ Gnanavel');",
"INSERT INTO authors (id, director) VALUES ('227', 'Уильям Фридкин');",
"INSERT INTO authors (id, director) VALUES ('228', 'Уильям Уайлер');",
"INSERT INTO authors (id, director) VALUES ('229', 'Брэд Бёрд');",
"INSERT INTO authors (id, director) VALUES ('230', 'Эрнст Любич');",
"INSERT INTO authors (id, director) VALUES ('231', 'Джилло Понтекорво');",
"INSERT INTO authors (id, director) VALUES ('232', 'Джон Форд');",
"INSERT INTO authors (id, director) VALUES ('233', 'Альфред Хичкок');",
"INSERT INTO authors (id, director) VALUES ('234', 'Лассе Халльстрём');",
"INSERT INTO authors (id, director) VALUES ('235', 'Гор Вербински');",
"INSERT INTO authors (id, director) VALUES ('236', 'Стюарт Розенберг');",
"INSERT INTO authors (id, director) VALUES ('237', 'Алехандро Гонсалес Иньярриту');",
"INSERT INTO authors (id, director) VALUES ('238', 'Матьё Кассовиц');",
"INSERT INTO authors (id, director) VALUES ('239', 'Чаган Ырмак');",
"INSERT INTO authors (id, director) VALUES ('240', 'Франсуа Трюффо');",
"INSERT INTO authors (id, director) VALUES ('241', 'Ингмар Бергман');",
"INSERT INTO authors (id, director) VALUES ('242', 'Фрэнк Капра');",
"INSERT INTO authors (id, director) VALUES ('243', 'Роберт Уайз');",
"INSERT INTO authors (id, director) VALUES ('244', 'Терри Джонс');",
"INSERT INTO authors (id, director) VALUES ('245', 'Пак Чхан Ук');",
"INSERT INTO authors (id, director) VALUES ('246', 'Акира Куросава');",
"INSERT INTO authors (id, director) VALUES ('247', 'Джон Маскер');",
"INSERT INTO authors (id, director) VALUES ('248', 'Ричард Аттенборо');",
"INSERT INTO authors (id, director) VALUES ('249', 'Тейт Тейлор');",
"INSERT INTO authors (id, director) VALUES ('250', 'Брэд Бёрд');"]
        for sql_command in sql_commands:
            cursor.execute(sql_command)

def fill_oscars(db):
    db.autocommit = True
    with db.cursor() as cursor:
        sql_commands = ["INSERT INTO oscars (year, film ) VALUES ('1929', 'Крылья');",
"INSERT INTO oscars (year, film ) VALUES ('1930', 'Бродвейская мелодия');",
"INSERT INTO oscars (year, film ) VALUES ('1931', 'На западном фронте без перемен');",
"INSERT INTO oscars (year, film ) VALUES ('1932', 'Симаррон');",
"INSERT INTO oscars (year, film ) VALUES ('1933', 'Гранд-отель');",
"INSERT INTO oscars (year, film ) VALUES ('1934', 'Кавалькада');",
"INSERT INTO oscars (year, film ) VALUES ('1935', 'Это случилось однажды ночью');",
"INSERT INTO oscars (year, film ) VALUES ('1936', 'Мятеж на „Баунти“');",
"INSERT INTO oscars (year, film ) VALUES ('1937', 'Великий Зигфелд');",
"INSERT INTO oscars (year, film ) VALUES ('1938', 'Жизнь Эмиля Золя');",
"INSERT INTO oscars (year, film ) VALUES ('1939', 'С собой не унесёшь');",
"INSERT INTO oscars (year, film ) VALUES ('1940', 'Унесённые ветром');",
"INSERT INTO oscars (year, film ) VALUES ('1941', 'Ребекка');",
"INSERT INTO oscars (year, film ) VALUES ('1942', 'Как зелена была моя долина');",
"INSERT INTO oscars (year, film ) VALUES ('1943', 'Миссис Минивер');",
"INSERT INTO oscars (year, film ) VALUES ('1944', 'Касабланка');",
"INSERT INTO oscars (year, film ) VALUES ('1945', 'Идти своим путём');",
"INSERT INTO oscars (year, film ) VALUES ('1946', 'Потерянный уикэнд');",
"INSERT INTO oscars (year, film ) VALUES ('1947', 'Лучшие годы нашей жизни');",
"INSERT INTO oscars (year, film ) VALUES ('1948', 'Джентльменское соглашение');",
"INSERT INTO oscars (year, film ) VALUES ('1949', 'Гамлет');",
"INSERT INTO oscars (year, film ) VALUES ('1950', 'Вся королевская рать');",
"INSERT INTO oscars (year, film ) VALUES ('1951', 'Всё о Еве');",
"INSERT INTO oscars (year, film ) VALUES ('1952', 'Американец в Париже');",
"INSERT INTO oscars (year, film ) VALUES ('1953', 'Величайшее шоу мира');",
"INSERT INTO oscars (year, film ) VALUES ('1954', 'Отныне и во веки веков');",
"INSERT INTO oscars (year, film ) VALUES ('1955', 'В порту');",
"INSERT INTO oscars (year, film ) VALUES ('1956', 'Марти');",
"INSERT INTO oscars (year, film ) VALUES ('1957', 'Вокруг света за 80 дней');",
"INSERT INTO oscars (year, film ) VALUES ('1958', 'Мост через реку Квай');",
"INSERT INTO oscars (year, film ) VALUES ('1959', 'Жижи');",
"INSERT INTO oscars (year, film ) VALUES ('1960', 'Бен-Гур');",
"INSERT INTO oscars (year, film ) VALUES ('1961', 'Квартира');",
"INSERT INTO oscars (year, film ) VALUES ('1962', 'Вестсайдская история');",
"INSERT INTO oscars (year, film ) VALUES ('1963', 'Лоуренс Аравийский');",
"INSERT INTO oscars (year, film ) VALUES ('1964', 'Том Джонс');",
"INSERT INTO oscars (year, film ) VALUES ('1965', 'Моя прекрасная леди');",
"INSERT INTO oscars (year, film ) VALUES ('1966', 'Звуки музыки');",
"INSERT INTO oscars (year, film ) VALUES ('1967', 'Человек на все времена');",
"INSERT INTO oscars (year, film ) VALUES ('1968', 'Душной южной ночью');",
"INSERT INTO oscars (year, film ) VALUES ('1969', 'Оливер!');",
"INSERT INTO oscars (year, film ) VALUES ('1970', 'Полуночный ковбой');",
"INSERT INTO oscars (year, film ) VALUES ('1971', 'Паттон');",
"INSERT INTO oscars (year, film ) VALUES ('1972', 'Французский связной');",
"INSERT INTO oscars (year, film ) VALUES ('1973', 'Крёстный отец');",
"INSERT INTO oscars (year, film ) VALUES ('1974', 'Афера');",
"INSERT INTO oscars (year, film ) VALUES ('1975', 'Крёстный отец 2');",
"INSERT INTO oscars (year, film ) VALUES ('1976', 'Пролетая над гнездом кукушки');",
"INSERT INTO oscars (year, film ) VALUES ('1977', 'Рокки');",
"INSERT INTO oscars (year, film ) VALUES ('1978', 'Энни Холл');",
"INSERT INTO oscars (year, film ) VALUES ('1979', 'Охотник на оленей');",
"INSERT INTO oscars (year, film ) VALUES ('1980', 'Крамер против Крамера');",
"INSERT INTO oscars (year, film ) VALUES ('1981', 'Обыкновенные люди');",
"INSERT INTO oscars (year, film ) VALUES ('1982', 'Огненные колесницы');",
"INSERT INTO oscars (year, film ) VALUES ('1983', 'Ганди');",
"INSERT INTO oscars (year, film ) VALUES ('1984', 'Язык нежности');",
"INSERT INTO oscars (year, film ) VALUES ('1985', 'Амадей');",
"INSERT INTO oscars (year, film ) VALUES ('1986', 'Из Африки');",
"INSERT INTO oscars (year, film ) VALUES ('1987', 'Взвод');",
"INSERT INTO oscars (year, film ) VALUES ('1988', 'Последний император');",
"INSERT INTO oscars (year, film ) VALUES ('1989', 'Человек дождя');",
"INSERT INTO oscars (year, film ) VALUES ('1990', 'Шофёр мисс Дэйзи');",
"INSERT INTO oscars (year, film ) VALUES ('1991', 'Танцующий с волками');",
"INSERT INTO oscars (year, film ) VALUES ('1992', 'Молчание ягнят');",
"INSERT INTO oscars (year, film ) VALUES ('1993', 'Непрощённый');",
"INSERT INTO oscars (year, film ) VALUES ('1994', 'Список Шиндлера');",
"INSERT INTO oscars (year, film ) VALUES ('1995', 'Форрест Гамп');",
"INSERT INTO oscars (year, film ) VALUES ('1996', 'Храброе сердце');",
"INSERT INTO oscars (year, film ) VALUES ('1997', 'Английский пациент');",
"INSERT INTO oscars (year, film ) VALUES ('1998', 'Титаник');",
"INSERT INTO oscars (year, film ) VALUES ('1999', 'Влюблённый Шекспир');",
"INSERT INTO oscars (year, film ) VALUES ('2000', 'Красота по-американски');",
"INSERT INTO oscars (year, film ) VALUES ('2001', 'Гладиатор');",
"INSERT INTO oscars (year, film ) VALUES ('2002', 'Игры разума');",
"INSERT INTO oscars (year, film ) VALUES ('2003', 'Чикаго');",
"INSERT INTO oscars (year, film ) VALUES ('2004', 'Властелин колец: Возвращение короля');",
"INSERT INTO oscars (year, film ) VALUES ('2005', 'Малышка на миллион');",
"INSERT INTO oscars (year, film ) VALUES ('2006', 'Столкновение');",
"INSERT INTO oscars (year, film ) VALUES ('2007', 'Отступники');",
"INSERT INTO oscars (year, film ) VALUES ('2008', 'Старикам тут не место');",
"INSERT INTO oscars (year, film ) VALUES ('2009', 'Миллионер из трущоб');",
"INSERT INTO oscars (year, film ) VALUES ('2010', 'Повелитель бури');",
"INSERT INTO oscars (year, film ) VALUES ('2011', 'Король говорит!');",
"INSERT INTO oscars (year, film ) VALUES ('2012', 'Артист');",
"INSERT INTO oscars (year, film ) VALUES ('2013', 'Операция „Арго“');",
"INSERT INTO oscars (year, film ) VALUES ('2014', '12 лет рабства');",
"INSERT INTO oscars (year, film ) VALUES ('2015', 'Бёрдмэн');",
"INSERT INTO oscars (year, film ) VALUES ('2016', 'В центре внимания');",
"INSERT INTO oscars (year, film ) VALUES ('2017', 'Лунный свет');",
"INSERT INTO oscars (year, film ) VALUES ('2018', 'Форма воды');",
"INSERT INTO oscars (year, film ) VALUES ('2019', 'Зелёная книга');",
"INSERT INTO oscars (year, film ) VALUES ('2020', 'Паразиты');",
"INSERT INTO oscars (year, film ) VALUES ('2021', 'Земля кочевников');",
"INSERT INTO oscars (year, film ) VALUES ('2022', 'CODA: Ребёнок глухих родителей');"]
        for sql_command in sql_commands:
            cursor.execute(sql_command)

def fill_actors(db):
    db.autocommit = True
    with db.cursor() as cursor:
        sql_commands = ["INSERT INTO actors (id, actor) VALUES ('1', 'Том Хэнкс');",
"INSERT INTO actors (id, actor) VALUES ('2', 'Лиам Нисон');",
"INSERT INTO actors (id, actor) VALUES ('3', 'Тим Роббинс');",
"INSERT INTO actors (id, actor) VALUES ('4', 'Том Хэнкс');",
"INSERT INTO actors (id, actor) VALUES ('5', 'Элайджа Вуд');",
"INSERT INTO actors (id, actor) VALUES ('6', 'Энтони Гонсалес');",
"INSERT INTO actors (id, actor) VALUES ('7', 'Майкл Дж. Фокс');",
"INSERT INTO actors (id, actor) VALUES ('8', 'Мэттью Макконахи');",
"INSERT INTO actors (id, actor) VALUES ('9', 'Джон Траволта');",
"INSERT INTO actors (id, actor) VALUES ('10', 'Элайджа Вуд');",
"INSERT INTO actors (id, actor) VALUES ('11', 'Элайджа Вуд');",
"INSERT INTO actors (id, actor) VALUES ('12', 'Александр Демьяненко');",
"INSERT INTO actors (id, actor) VALUES ('13', 'Франсуа Клозе');",
"INSERT INTO actors (id, actor) VALUES ('14', 'Мэттью Бродерик');",
"INSERT INTO actors (id, actor) VALUES ('15', 'Кристиан Бэйл');",
"INSERT INTO actors (id, actor) VALUES ('16', 'Эдвард Нортан');",
"INSERT INTO actors (id, actor) VALUES ('17', 'Руми Хиираги');",
"INSERT INTO actors (id, actor) VALUES ('18', 'Василий Ливанов');",
"INSERT INTO actors (id, actor) VALUES ('19', 'Бен Бертт');",
"INSERT INTO actors (id, actor) VALUES ('20', 'Рассел Клоу');",
"INSERT INTO actors (id, actor) VALUES ('21', 'Вера Алентова');",
"INSERT INTO actors (id, actor) VALUES ('22', 'Евгений Леонов');",
"INSERT INTO actors (id, actor) VALUES ('23', 'Майк Майерс');",
"INSERT INTO actors (id, actor) VALUES ('24', 'Тиль Швайгер');",
"INSERT INTO actors (id, actor) VALUES ('25', 'Джонни Депп');",
"INSERT INTO actors (id, actor) VALUES ('26', 'Леонардо ДиКаприо');",
"INSERT INTO actors (id, actor) VALUES ('27', 'Леонардо ДиКаприо');",
"INSERT INTO actors (id, actor) VALUES ('28', 'Елена Драпеко');",
"INSERT INTO actors (id, actor) VALUES ('29', 'Василий Шукшин');",
"INSERT INTO actors (id, actor) VALUES ('30', 'Джейсон Стейтом');",
"INSERT INTO actors (id, actor) VALUES ('31', 'Дэниел Рэдклифф');",
"INSERT INTO actors (id, actor) VALUES ('32', 'Владимир Заднепровский');",
"INSERT INTO actors (id, actor) VALUES ('33', 'Леонардо ДиКаприо');",
"INSERT INTO actors (id, actor) VALUES ('34', 'Леонид Быков');",
"INSERT INTO actors (id, actor) VALUES ('35', 'Мэттью Макконахи');",
"INSERT INTO actors (id, actor) VALUES ('36', 'Эндрю Гарфилд');",
"INSERT INTO actors (id, actor) VALUES ('37', 'Леонардо ДиКаприо');",
"INSERT INTO actors (id, actor) VALUES ('38', 'Дэниел Рэдклифф');",
"INSERT INTO actors (id, actor) VALUES ('39', 'Джейсон Флеминг');",
"INSERT INTO actors (id, actor) VALUES ('40', 'Александр Демьяненко');",
"INSERT INTO actors (id, actor) VALUES ('41', 'Эмма Стоун');",
"INSERT INTO actors (id, actor) VALUES ('42', 'Надежда Румянцева');",
"INSERT INTO actors (id, actor) VALUES ('43', 'Тиэко Байсе');",
"INSERT INTO actors (id, actor) VALUES ('44', 'Сергей Бодров');",
"INSERT INTO actors (id, actor) VALUES ('45', 'Джейсон Шварцман');",
"INSERT INTO actors (id, actor) VALUES ('46', 'Арнольд Шварценеггер');",
"INSERT INTO actors (id, actor) VALUES ('47', 'Владимир Толоконников');",
"INSERT INTO actors (id, actor) VALUES ('48', 'Джейми Фокс');",
"INSERT INTO actors (id, actor) VALUES ('49', 'Роберто Бениньи');",
"INSERT INTO actors (id, actor) VALUES ('50', 'Василий Ливанов');",
"INSERT INTO actors (id, actor) VALUES ('51', 'Майкл Дж. Фокс');",
"INSERT INTO actors (id, actor) VALUES ('52', 'Георгий Юматов');",
"INSERT INTO actors (id, actor) VALUES ('53', 'Жан Рено');",
"INSERT INTO actors (id, actor) VALUES ('54', 'Сергей Бодров');",
"INSERT INTO actors (id, actor) VALUES ('55', 'Марлон Брандо');",
"INSERT INTO actors (id, actor) VALUES ('56', 'Андрей Мягков');",
"INSERT INTO actors (id, actor) VALUES ('57', 'Вигго Мортенсен');",
"INSERT INTO actors (id, actor) VALUES ('58', 'Ричард Гир');",
"INSERT INTO actors (id, actor) VALUES ('59', 'Джонни Депп');",
"INSERT INTO actors (id, actor) VALUES ('60', 'Аль Пачино');",
"INSERT INTO actors (id, actor) VALUES ('61', 'Юрий Никулин');",
"INSERT INTO actors (id, actor) VALUES ('62', 'Сергей Бондарчук');",
"INSERT INTO actors (id, actor) VALUES ('63', 'Дэниэл Рэдклифф');",
"INSERT INTO actors (id, actor) VALUES ('64', 'Джиннифер Гудвин');",
"INSERT INTO actors (id, actor) VALUES ('65', 'Эдриан Броуди');",
"INSERT INTO actors (id, actor) VALUES ('66', 'Джей Барушель');",
"INSERT INTO actors (id, actor) VALUES ('67', 'Пэттой Освальт');",
"INSERT INTO actors (id, actor) VALUES ('68', 'Маколей Калкин');",
"INSERT INTO actors (id, actor) VALUES ('69', 'Александр Демьяненко');",
"INSERT INTO actors (id, actor) VALUES ('70', 'Киану Ривз');",
"INSERT INTO actors (id, actor) VALUES ('71', 'Аль Пачино');",
"INSERT INTO actors (id, actor) VALUES ('72', 'Кристиан Бэйл');",
"INSERT INTO actors (id, actor) VALUES ('73', 'Майкл Дж. Фокс');",
"INSERT INTO actors (id, actor) VALUES ('74', 'Дэниэл Рэдклифф');",
"INSERT INTO actors (id, actor) VALUES ('75', 'Рюносукэ Камики');",
"INSERT INTO actors (id, actor) VALUES ('76', 'Юэн Макгрегор');",
"INSERT INTO actors (id, actor) VALUES ('77', 'Адриано Челентано');",
"INSERT INTO actors (id, actor) VALUES ('78', 'Эдди Мерфи');",
"INSERT INTO actors (id, actor) VALUES ('79', 'Дэвид Роул');",
"INSERT INTO actors (id, actor) VALUES ('80', 'Джон Гудман');",
"INSERT INTO actors (id, actor) VALUES ('81', 'Уилл Смит');",
"INSERT INTO actors (id, actor) VALUES ('82', 'Алексей Кравченко');",
"INSERT INTO actors (id, actor) VALUES ('83', 'Александр Михайлов');",
"INSERT INTO actors (id, actor) VALUES ('84', 'Хью Джекман');",
"INSERT INTO actors (id, actor) VALUES ('85', 'Майк Майерс');",
"INSERT INTO actors (id, actor) VALUES ('86', 'Джим Керри');",
"INSERT INTO actors (id, actor) VALUES ('87', 'Джонни Депп');",
"INSERT INTO actors (id, actor) VALUES ('88', 'Майлз Теллер');",
"INSERT INTO actors (id, actor) VALUES ('89', 'Леонардо ДиКаприо');",
"INSERT INTO actors (id, actor) VALUES ('90', 'Александр Михайлов');",
"INSERT INTO actors (id, actor) VALUES ('91', 'Уилл Смит');",
"INSERT INTO actors (id, actor) VALUES ('92', 'Едзи Мацуда');",
"INSERT INTO actors (id, actor) VALUES ('93', 'Мэл Гибсон');",
"INSERT INTO actors (id, actor) VALUES ('94', 'Скотт Венгер');",
"INSERT INTO actors (id, actor) VALUES ('95', 'Генри Фонда');",
"INSERT INTO actors (id, actor) VALUES ('96', 'Василий Ливанов');",
"INSERT INTO actors (id, actor) VALUES ('97', 'Олег Янковский');",
"INSERT INTO actors (id, actor) VALUES ('98', 'Татьяна Самойлова');",
"INSERT INTO actors (id, actor) VALUES ('99', 'Рольф Лассгор');",
"INSERT INTO actors (id, actor) VALUES ('100', 'Мартин Фриман');",
"INSERT INTO actors (id, actor) VALUES ('101', 'Том Хэнкс');",
"INSERT INTO actors (id, actor) VALUES ('102', 'Лиам Нисон');",
"INSERT INTO actors (id, actor) VALUES ('103', 'Тим Роббинс');",
"INSERT INTO actors (id, actor) VALUES ('104', 'Том Хэнкс');",
"INSERT INTO actors (id, actor) VALUES ('105', 'Элайджа Вуд');",
"INSERT INTO actors (id, actor) VALUES ('106', 'Энтони Гонсалес');",
"INSERT INTO actors (id, actor) VALUES ('107', 'Майкл Дж. Фокс');",
"INSERT INTO actors (id, actor) VALUES ('108', 'Мэттью Макконахи');",
"INSERT INTO actors (id, actor) VALUES ('109', 'Джон Траволта');",
"INSERT INTO actors (id, actor) VALUES ('110', 'Элайджа Вуд');",
"INSERT INTO actors (id, actor) VALUES ('111', 'Элайджа Вуд');",
"INSERT INTO actors (id, actor) VALUES ('112', 'Александр Демьяненко');",
"INSERT INTO actors (id, actor) VALUES ('113', 'Франсуа Клозе');",
"INSERT INTO actors (id, actor) VALUES ('114', 'Мэттью Бродерик');",
"INSERT INTO actors (id, actor) VALUES ('115', 'Кристиан Бэйл');",
"INSERT INTO actors (id, actor) VALUES ('116', 'Эдвард Нортан');",
"INSERT INTO actors (id, actor) VALUES ('117', 'Руми Хиираги');",
"INSERT INTO actors (id, actor) VALUES ('118', 'Василий Ливанов');",
"INSERT INTO actors (id, actor) VALUES ('119', 'Бен Бертт');",
"INSERT INTO actors (id, actor) VALUES ('120', 'Рассел Клоу');",
"INSERT INTO actors (id, actor) VALUES ('121', 'Вера Алентова');",
"INSERT INTO actors (id, actor) VALUES ('122', 'Евгений Леонов');",
"INSERT INTO actors (id, actor) VALUES ('123', 'Майк Майерс');",
"INSERT INTO actors (id, actor) VALUES ('124', 'Тиль Швайгер');",
"INSERT INTO actors (id, actor) VALUES ('125', 'Джонни Депп');",
"INSERT INTO actors (id, actor) VALUES ('126', 'Леонардо ДиКаприо');",
"INSERT INTO actors (id, actor) VALUES ('127', 'Леонардо ДиКаприо');",
"INSERT INTO actors (id, actor) VALUES ('128', 'Елена Драпеко');",
"INSERT INTO actors (id, actor) VALUES ('129', 'Василий Шукшин');",
"INSERT INTO actors (id, actor) VALUES ('130', 'Джейсон Стейтом');",
"INSERT INTO actors (id, actor) VALUES ('131', 'Дэниел Рэдклифф');",
"INSERT INTO actors (id, actor) VALUES ('132', 'Владимир Заднепровский');",
"INSERT INTO actors (id, actor) VALUES ('133', 'Леонардо ДиКаприо');",
"INSERT INTO actors (id, actor) VALUES ('134', 'Леонид Быков');",
"INSERT INTO actors (id, actor) VALUES ('135', 'Мэттью Макконахи');",
"INSERT INTO actors (id, actor) VALUES ('136', 'Эндрю Гарфилд');",
"INSERT INTO actors (id, actor) VALUES ('137', 'Леонардо ДиКаприо');",
"INSERT INTO actors (id, actor) VALUES ('138', 'Дэниел Рэдклифф');",
"INSERT INTO actors (id, actor) VALUES ('139', 'Джейсон Флеминг');",
"INSERT INTO actors (id, actor) VALUES ('140', 'Александр Демьяненко');",
"INSERT INTO actors (id, actor) VALUES ('141', 'Эмма Стоун');",
"INSERT INTO actors (id, actor) VALUES ('142', 'Надежда Румянцева');",
"INSERT INTO actors (id, actor) VALUES ('143', 'Тиэко Байсе');",
"INSERT INTO actors (id, actor) VALUES ('144', 'Сергей Бодров');",
"INSERT INTO actors (id, actor) VALUES ('145', 'Джейсон Шварцман');",
"INSERT INTO actors (id, actor) VALUES ('146', 'Арнольд Шварценеггер');",
"INSERT INTO actors (id, actor) VALUES ('147', 'Владимир Толоконников');",
"INSERT INTO actors (id, actor) VALUES ('148', 'Джейми Фокс');",
"INSERT INTO actors (id, actor) VALUES ('149', 'Роберто Бениньи');",
"INSERT INTO actors (id, actor) VALUES ('150', 'Василий Ливанов');",
"INSERT INTO actors (id, actor) VALUES ('151', 'Майкл Дж. Фокс');",
"INSERT INTO actors (id, actor) VALUES ('152', 'Георгий Юматов');",
"INSERT INTO actors (id, actor) VALUES ('153', 'Жан Рено');",
"INSERT INTO actors (id, actor) VALUES ('154', 'Сергей Бодров');",
"INSERT INTO actors (id, actor) VALUES ('155', 'Марлон Брандо');",
"INSERT INTO actors (id, actor) VALUES ('156', 'Андрей Мягков');",
"INSERT INTO actors (id, actor) VALUES ('157', 'Вигго Мортенсен');",
"INSERT INTO actors (id, actor) VALUES ('158', 'Ричард Гир');",
"INSERT INTO actors (id, actor) VALUES ('159', 'Джонни Депп');",
"INSERT INTO actors (id, actor) VALUES ('160', 'Аль Пачино');",
"INSERT INTO actors (id, actor) VALUES ('161', 'Юрий Никулин');",
"INSERT INTO actors (id, actor) VALUES ('162', 'Сергей Бондарчук');",
"INSERT INTO actors (id, actor) VALUES ('163', 'Дэниэл Рэдклифф');",
"INSERT INTO actors (id, actor) VALUES ('164', 'Джиннифер Гудвин');",
"INSERT INTO actors (id, actor) VALUES ('165', 'Эдриан Броуди');",
"INSERT INTO actors (id, actor) VALUES ('166', 'Джей Барушель');",
"INSERT INTO actors (id, actor) VALUES ('167', 'Пэттой Освальт');",
"INSERT INTO actors (id, actor) VALUES ('168', 'Маколей Калкин');",
"INSERT INTO actors (id, actor) VALUES ('169', 'Александр Демьяненко');",
"INSERT INTO actors (id, actor) VALUES ('170', 'Киану Ривз');",
"INSERT INTO actors (id, actor) VALUES ('171', 'Аль Пачино');",
"INSERT INTO actors (id, actor) VALUES ('172', 'Кристиан Бэйл');",
"INSERT INTO actors (id, actor) VALUES ('173', 'Майкл Дж. Фокс');",
"INSERT INTO actors (id, actor) VALUES ('174', 'Дэниэл Рэдклифф');",
"INSERT INTO actors (id, actor) VALUES ('175', 'Рюносукэ Камики');",
"INSERT INTO actors (id, actor) VALUES ('176', 'Юэн Макгрегор');",
"INSERT INTO actors (id, actor) VALUES ('177', 'Адриано Челентано');",
"INSERT INTO actors (id, actor) VALUES ('178', 'Эдди Мерфи');",
"INSERT INTO actors (id, actor) VALUES ('179', 'Дэвид Роул');",
"INSERT INTO actors (id, actor) VALUES ('180', 'Джон Гудман');",
"INSERT INTO actors (id, actor) VALUES ('181', 'Уилл Смит');",
"INSERT INTO actors (id, actor) VALUES ('182', 'Алексей Кравченко');",
"INSERT INTO actors (id, actor) VALUES ('183', 'Александр Михайлов');",
"INSERT INTO actors (id, actor) VALUES ('184', 'Хью Джекман');",
"INSERT INTO actors (id, actor) VALUES ('185', 'Майк Майерс');",
"INSERT INTO actors (id, actor) VALUES ('186', 'Джим Керри');",
"INSERT INTO actors (id, actor) VALUES ('187', 'Джонни Депп');",
"INSERT INTO actors (id, actor) VALUES ('188', 'Майлз Теллер');",
"INSERT INTO actors (id, actor) VALUES ('189', 'Леонардо ДиКаприо');",
"INSERT INTO actors (id, actor) VALUES ('190', 'Александр Михайлов');",
"INSERT INTO actors (id, actor) VALUES ('191', 'Уилл Смит');",
"INSERT INTO actors (id, actor) VALUES ('192', 'Едзи Мацуда');",
"INSERT INTO actors (id, actor) VALUES ('193', 'Мэл Гибсон');",
"INSERT INTO actors (id, actor) VALUES ('194', 'Скотт Венгер');",
"INSERT INTO actors (id, actor) VALUES ('195', 'Генри Фонда');",
"INSERT INTO actors (id, actor) VALUES ('196', 'Василий Ливанов');",
"INSERT INTO actors (id, actor) VALUES ('197', 'Олег Янковский');",
"INSERT INTO actors (id, actor) VALUES ('198', 'Татьяна Самойлова');",
"INSERT INTO actors (id, actor) VALUES ('199', 'Рольф Лассгор');",
"INSERT INTO actors (id, actor) VALUES ('200', 'Мартин Фриман');",
"INSERT INTO actors (id, actor) VALUES ('201', 'Василий Ливанов');",
"INSERT INTO actors (id, actor) VALUES ('202', 'Майкл Дж. Фокс');",
"INSERT INTO actors (id, actor) VALUES ('203', 'Георгий Юматов');",
"INSERT INTO actors (id, actor) VALUES ('204', 'Жан Рено');",
"INSERT INTO actors (id, actor) VALUES ('205', 'Сергей Бодров');",
"INSERT INTO actors (id, actor) VALUES ('206', 'Марлон Брандо');",
"INSERT INTO actors (id, actor) VALUES ('207', 'Андрей Мягков');",
"INSERT INTO actors (id, actor) VALUES ('208', 'Вигго Мортенсен');",
"INSERT INTO actors (id, actor) VALUES ('209', 'Ричард Гир');",
"INSERT INTO actors (id, actor) VALUES ('210', 'Джонни Депп');",
"INSERT INTO actors (id, actor) VALUES ('211', 'Аль Пачино');",
"INSERT INTO actors (id, actor) VALUES ('212', 'Юрий Никулин');",
"INSERT INTO actors (id, actor) VALUES ('213', 'Сергей Бондарчук');",
"INSERT INTO actors (id, actor) VALUES ('214', 'Дэниэл Рэдклифф');",
"INSERT INTO actors (id, actor) VALUES ('215', 'Джиннифер Гудвин');",
"INSERT INTO actors (id, actor) VALUES ('216', 'Эдриан Броуди');",
"INSERT INTO actors (id, actor) VALUES ('217', 'Джей Барушель');",
"INSERT INTO actors (id, actor) VALUES ('218', 'Пэттой Освальт');",
"INSERT INTO actors (id, actor) VALUES ('219', 'Маколей Калкин');",
"INSERT INTO actors (id, actor) VALUES ('220', 'Александр Демьяненко');",
"INSERT INTO actors (id, actor) VALUES ('221', 'Киану Ривз');",
"INSERT INTO actors (id, actor) VALUES ('222', 'Аль Пачино');",
"INSERT INTO actors (id, actor) VALUES ('223', 'Кристиан Бэйл');",
"INSERT INTO actors (id, actor) VALUES ('224', 'Майкл Дж. Фокс');",
"INSERT INTO actors (id, actor) VALUES ('225', 'Дэниэл Рэдклифф');",
"INSERT INTO actors (id, actor) VALUES ('226', 'Рюносукэ Камики');",
"INSERT INTO actors (id, actor) VALUES ('227', 'Юэн Макгрегор');",
"INSERT INTO actors (id, actor) VALUES ('228', 'Адриано Челентано');",
"INSERT INTO actors (id, actor) VALUES ('229', 'Эдди Мерфи');",
"INSERT INTO actors (id, actor) VALUES ('230', 'Дэвид Роул');",
"INSERT INTO actors (id, actor) VALUES ('231', 'Джон Гудман');",
"INSERT INTO actors (id, actor) VALUES ('232', 'Уилл Смит');",
"INSERT INTO actors (id, actor) VALUES ('233', 'Алексей Кравченко');",
"INSERT INTO actors (id, actor) VALUES ('234', 'Александр Михайлов');",
"INSERT INTO actors (id, actor) VALUES ('235', 'Хью Джекман');",
"INSERT INTO actors (id, actor) VALUES ('236', 'Майк Майерс');",
"INSERT INTO actors (id, actor) VALUES ('237', 'Джим Керри');",
"INSERT INTO actors (id, actor) VALUES ('238', 'Джонни Депп');",
"INSERT INTO actors (id, actor) VALUES ('239', 'Майлз Теллер');",
"INSERT INTO actors (id, actor) VALUES ('240', 'Леонардо ДиКаприо');",
"INSERT INTO actors (id, actor) VALUES ('241', 'Александр Михайлов');",
"INSERT INTO actors (id, actor) VALUES ('242', 'Уилл Смит');",
"INSERT INTO actors (id, actor) VALUES ('243', 'Едзи Мацуда');",
"INSERT INTO actors (id, actor) VALUES ('244', 'Мэл Гибсон');",
"INSERT INTO actors (id, actor) VALUES ('245', 'Скотт Венгер');",
"INSERT INTO actors (id, actor) VALUES ('246', 'Генри Фонда');",
"INSERT INTO actors (id, actor) VALUES ('247', 'Василий Ливанов');",
"INSERT INTO actors (id, actor) VALUES ('248', 'Олег Янковский');",
"INSERT INTO actors (id, actor) VALUES ('249', 'Татьяна Самойлова');",
"INSERT INTO actors (id, actor) VALUES ('250', 'Рольф Лассгор');"]
        for sql_command in sql_commands:
            cursor.execute(sql_command)

create_db(db)
fill_topfilm(db)
fill_oscars(db)
fill_authors(db)
fill_scores(db)
fill_trivia(db)
fill_actors(db)
